name: symbiote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_messaging: ^14.7.9
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  cloud_firestore: ^4.15.9
  encrypt: ^5.0.3
  crypto: ^3.0.3
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.0+4
  http: ^1.1.0
  flutter_vertical_heatmap: ^1.0.3
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.1
  share_plus: ^10.0.0
  local_auth: ^2.3.0
  pinput: ^5.0.1
  flutter_dotenv: ^5.2.1
  gpt_markdown: ^1.0.20
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"

flutter_native_splash:
  background_image: "assets/images/splash.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/splash_android12.png" 
    color: "#311b92" 
    icon_background_color: "#311b92" 