name: symbiote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_messaging: ^14.7.9
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  cloud_firestore: ^4.15.9
  encrypt: ^5.0.3
  crypto: ^3.0.3
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.0+4
  http: ^1.1.0
  flutter_vertical_heatmap: ^1.0.3
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
